### ISSUE TITLE
podcast06: VRについて

### ISSUE THREAD

**Issue by yorisilo** [yorisilo/yorisilo.github.io#2]
# 話すこと

* “バーチャル“リアリティと リアリティ、１回性、痛み、死ぬことについて
ブラジリアンワックスをしてて気づいたこと

**Comment by midorizemi** [comment]
どんなことをはなすんだい？

**Comment by yorisilo** [comment]
oculus go をやっていて思ったこと。

ブラジリアンワックスをしてて、現実の痛みに対して、は及ばないと思った。

VR を体験している最中、それが実際に目の前で起こっているように感じるが、
現実世界で、ゴーグルをかぶっている自分が、なにかたとえば、刺されてしまった場合、
VRから離脱せざるを得ない。

実際に現実で起こっていること、切実なこと、例えば、痛み、死ぬことそれにはVRは及ばない。
VRでは死を体験することはできても、もちろん、死を実際に体験することはできない。
それはあくまでも擬似的なものであって、現実ではない。

いくらVRが現実に限りなく近い解像度持って我々に挑んできても、我々は、身体を持っている。
痛みを感じる体を持っている。
VRに閉じこもることができないのは、それがほとんどの原因だ。食べなければ生きていけない。
その乖離に対して、どうやって対処すればいいのだろうか。

ready player 1  では、VR と現実はきちんとわけるべきという世界を提示した。
VRはあくまでも娯楽に過ぎないと。一回性の人生を生きろとスピルバーグは言った。
それはわかりやすい教訓ではあるが、その方向しかないのだろうか。

**Comment by yorisilo** [comment]
池の上駅で降りて、とんかつを食べて、駒場東大の60号館へ(めちゃ新しい)
* Parametric Move 動きをうごかす展
https://fabcross.jp/topics/event_report/20180611_parametric_move.html
http://www.design-lab.iis.u-tokyo.ac.jp/exhibition/proto2018/

* SEER 美少女2.5次元眉毛まぶた眼球動くロボット
https://pc.watch.impress.co.jp/docs/column/kyokai/1127213.html

**Comment by midorizemi** [comment]
issue閉じてええんとちゃう
